### PR TITLE
[WIP] add new rotation option

### PR DESCRIPTION
**Pull request by smknstd**
Peek 2020-07-16 14-31

Not sure if it should rotate svg while exporting, what do you think ?

### CODE REVIEW

**Comment by georgedoescode** [comment]
Hey @smknstd ! Amazing work, looking great so far. Couple small of things from me would be: 

Looking at the deploy preview, the dashed squircle preview is no longer a square due to the increased height of the control panel, the dimensions of the generator panel also look a little off due to the added slider. I think a good solution would simply be to increase the generator width (its currently 56rem)  / its `grid-template-columns` so that the controls are always slightly shorter than the preview (see live site) and the preview remains a square.

Also it would be nice if the rotation slider initialised in the center and rotate say -90/+90 either side. What do you think? 

Again thanks so much for contributing and let me know if there is anything I can help with at all, just ask :) 

Cheers!

**Comment by smknstd** [comment]
Screenshot from 2020-07-18 10-54-25

I don't know how css grid works, but I think I managed something. I made the generator width from `56rem` to `60rem` and the preview div went from `368px` to `418px`.

I also changed the rotation slider. I made it -45/45, so it is initialized in the middle.

**Comment by georgedoescode** [comment]
@smknstd Looking great with the slider centred! Perfect on that front. Works really well and im sure will add a lot of value to our users. There are still a couple of CSS issues for me, for example the SVG preview is now a bit large, and the controls look too narrow. Also as the width of the generator has been increased to 60rem, there are some breakpoints that need to be adjusted. 

I am happy to branch off your work and make the tweaks if you're not too familiar with grid? The JS stuff is absolutely perfect its just a couple of styling bits, I also appreciate I am fairly picky, so thank you for being patient 🙏 

Just let me know :)

**Comment by smknstd** [comment]
No problem at all. Please branch off. 

There is still one question remaining. Do you think the exported svg needs to be rotated as well as the preview ?

**Comment by georgedoescode** [comment]
@smknstd Nice one, I'll get that done ASAP. I would say yes, whatever is seen in the preview should be exactly the same as what is exported :)

**Comment by smknstd** [comment]
I'll try to fix the exported SVG then. I'll try somethig like `path.setAttribute('transform', 'rotate(...)');`

Apparently you can update my PR directly (no need to branching or something): https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by georgedoescode** [comment]
@smknstd Great spot, nice one :) Sounds good, interesting that the `scale` transform is exported fine but the rotation is not. Let me know how it goes anyway, i'll try and do the CSS this evening!

**Comment by georgedoescode** [comment]
@smknstd Styles updated! I noticed a proptype error whilst working on them that might be worth checking out, but once that's all good / the rotation value exports this can go to master 🎉

**Comment by smknstd** [comment]
Great! I'll try to work on this next weekend

**Comment by smknstd** [comment]
>  interesting that the scale transform is exported fine but the rotation is not

Scale is not exported either, you use scale parameter when setting svg path:

```
this.setPath(
                this.squircleOpts.scale,
                this.squircleOpts.scale,
                this.squircleOpts.curvature
            );
```
Ending with a transform attribute in final svg seems not a good idea:

Screenshot from 2020-07-25 17-00-11

Problem is harder than I thought. I think there is only two options:
- drawing initial svg path already rotated (and not doing anything more while exporting)
- keeping `transform: rotate()`  in preview but when exporting we get a new svg with a tool like: https://gist.github.com/timo22345/9413158

**Comment by georgedoescode** [comment]
@smknstd Just checked and weirdly, although the `scale` transform is not actually applied to saved SVGs, they do export correctly with the scale you apply. 

Anyway, I don't see any issue with just applying the `transform` to the path on export. Have seen lots of other tools do this and definitely seems like the simplest solution :)

**Comment by georgedoescode** [comment]
@smknstd Should be all good now :) Let me know if you are happy with the deploy preview and we will get this into master!

**Comment by georgedoescode** [comment]
@smknstd Bump! Be good to get this released but I don't want to push your work without your OK :)

**Comment by smknstd** [comment]
No problem for me if you think it is ok :+1:  Good work !

**Comment by georgedoescode** [comment]
@smknstd Awesome :) You too! Thanks again for contributing. Merging to master 🚀

**Pull request merged**
